from __future__ import annotations

import datetime
from pathlib import Path

_SKIP_DIRS: frozenset[str] = frozenset({
    ".git", ".obsidian", "PDFs", "Attachments",
    "Copilot", "__pycache__", ".venv", ".venv_test",
})
_OUTPUT = Path("Manifests/vault-structure.md")

_FRONTMATTER = """\
---
id: "vault-structure"
title: "Vault File Structure"
type: "manifest"
status: "active"
created: "2026-05-15"
updated: "{updated}"
aliases: []
tags: ["manifest", "structure"]
projects: []
publish: false
related: []
sources: []
---
"""


def _should_skip(rel_parts: tuple[str, ...]) -> bool:
    return any(p in _SKIP_DIRS or p.startswith(".") for p in rel_parts)


def _build_tree(vault_root: Path) -> tuple[list[str], dict[str, int], int]:
    """Return (tree_lines, dir_counts, total_md)."""
    lines: list[str] = []
    dir_counts: dict[str, int] = {}
    total_md = 0

    def walk(directory: Path, prefix: str) -> None:
        nonlocal total_md
        try:
            entries = sorted(directory.iterdir(), key=lambda p: (p.is_file(), p.name.lower()))
        except PermissionError:
            return

        dirs = [e for e in entries if e.is_dir() and not _should_skip(e.relative_to(vault_root).parts)]
        files = [e for e in entries if e.is_file() and e.suffix == ".md"
                 and not _should_skip(e.relative_to(vault_root).parts[:-1])]

        all_items = dirs + files
        for i, entry in enumerate(all_items):
            connector = "└── " if i == len(all_items) - 1 else "├── "
            extension = "    " if i == len(all_items) - 1 else "│   "
            if entry.is_dir():
                lines.append(f"{prefix}{connector}{entry.name}/")
                walk(entry, prefix + extension)
            else:
                lines.append(f"{prefix}{connector}{entry.name}")
                total_md += 1

        md_count = len(files)
        if md_count:
            key = str(directory.relative_to(vault_root)) if directory != vault_root else "."
            dir_counts[key] = md_count

    lines.append(f"{vault_root.name}/")
    walk(vault_root, "")
    return lines, dir_counts, total_md


def generate_vault_structure(vault_root: Path) -> Path:
    """Write Manifests/vault-structure.md and return its path."""
    out = vault_root / _OUTPUT
    out.parent.mkdir(parents=True, exist_ok=True)

    now = datetime.datetime.now(tz=datetime.timezone.utc)
    updated = now.strftime("%Y-%m-%d")
    timestamp = now.strftime("%Y-%m-%d %H:%M UTC")

    tree_lines, dir_counts, total_md = _build_tree(vault_root)
    total_dirs = sum(1 for _ in vault_root.rglob("*")
                     if _.is_dir() and not _should_skip(_.relative_to(vault_root).parts))

    # Build summary table sorted by file count descending
    summary_rows = "\n".join(
        f"| `{d}` | {n} |"
        for d, n in sorted(dir_counts.items(), key=lambda x: -x[1])
    )

    content = _FRONTMATTER.format(updated=updated)
    content += f"""
# Vault File Structure

> Auto-generated by `lint-wiki`. Last updated: {timestamp}

## Summary

| Metric | Value |
| --- | --- |
| Total markdown files | {total_md} |
| Total directories | {total_dirs} |

## Files per Directory

| Directory | Markdown files |
| --- | --- |
{summary_rows}

## Full Tree

```
{chr(10).join(tree_lines)}
```
"""

    out.write_text(content, encoding="utf-8")
    return out
